/**
 * ZMK firmware generator.
 *
 * Generates devicetree overlay, keymap, config, and metadata files
 * for a ZMK-based keyboard firmware build.
 */

import type { KeyboardLayout, SwitchMatrix, BuildConfig } from '../shared/types.js';

export interface FirmwareOutput {
  /** ZMK devicetree overlay (.overlay) */
  overlay: string;
  /** ZMK keymap file (.keymap) */
  keymap: string;
  /** ZMK config file (.conf) */
  conf: string;
  /** ZMK metadata file (.zmk.yml) */
  metadata: string;
}

/** Mapping from common KLE labels to ZMK keycode names */
const LABEL_TO_ZMK: Record<string, string> = {
  // Letters
  A: 'A', B: 'B', C: 'C', D: 'D', E: 'E', F: 'F', G: 'G', H: 'H',
  I: 'I', J: 'J', K: 'K', L: 'L', M: 'M', N: 'N', O: 'O', P: 'P',
  Q: 'Q', R: 'R', S: 'S', T: 'T', U: 'U', V: 'V', W: 'W', X: 'X',
  Y: 'Y', Z: 'Z',
  // Numbers
  '1': 'N1', '2': 'N2', '3': 'N3', '4': 'N4', '5': 'N5',
  '6': 'N6', '7': 'N7', '8': 'N8', '9': 'N9', '0': 'N0',
  // F-keys
  F1: 'F1', F2: 'F2', F3: 'F3', F4: 'F4', F5: 'F5', F6: 'F6',
  F7: 'F7', F8: 'F8', F9: 'F9', F10: 'F10', F11: 'F11', F12: 'F12',
  // Modifiers
  Ctrl: 'LCTRL', Control: 'LCTRL', LCtrl: 'LCTRL', RCtrl: 'RCTRL',
  Shift: 'LSHIFT', LShift: 'LSHIFT', RShift: 'RSHIFT',
  Alt: 'LALT', LAlt: 'LALT', RAlt: 'RALT',
  Win: 'LGUI', GUI: 'LGUI', Super: 'LGUI', Meta: 'LGUI', Cmd: 'LGUI',
  // Special keys
  Esc: 'ESC', Escape: 'ESC',
  Tab: 'TAB',
  Caps: 'CAPS', CapsLock: 'CAPS', 'Caps Lock': 'CAPS',
  Enter: 'RET', Return: 'RET',
  Backspace: 'BSPC', BkSp: 'BSPC', Bksp: 'BSPC',
  Space: 'SPACE', ' ': 'SPACE',
  Del: 'DEL', Delete: 'DEL',
  Ins: 'INS', Insert: 'INS',
  Home: 'HOME',
  End: 'END',
  PgUp: 'PG_UP', 'Page Up': 'PG_UP',
  PgDn: 'PG_DN', 'Page Down': 'PG_DN',
  // Arrows
  Up: 'UP', Down: 'DOWN', Left: 'LEFT', Right: 'RIGHT',
  '\u2191': 'UP', '\u2193': 'DOWN', '\u2190': 'LEFT', '\u2192': 'RIGHT',
  // Punctuation
  '-': 'MINUS', '=': 'EQUAL', '[': 'LBKT', ']': 'RBKT',
  '\\': 'BSLH', ';': 'SEMI', "'": 'SQT', '`': 'GRAVE',
  ',': 'COMMA', '.': 'DOT', '/': 'FSLH',
  // Print screen, scroll lock, pause
  PrtSc: 'PSCRN', 'Print Screen': 'PSCRN',
  ScrLk: 'SLCK', 'Scroll Lock': 'SLCK',
  Pause: 'PAUSE_BREAK',
  // Menu
  Menu: 'K_APP', App: 'K_APP',
  // Fn
  Fn: 'TRANS',
};

/**
 * Look up a ZMK keycode for a KLE label.
 */
function labelToZmkKeycode(label: string): string {
  if (!label || label.trim() === '') return 'TRANS';
  const trimmed = label.trim();
  // Direct match
  if (LABEL_TO_ZMK[trimmed]) return LABEL_TO_ZMK[trimmed];
  // Case-insensitive match
  const upper = trimmed.toUpperCase();
  for (const [key, value] of Object.entries(LABEL_TO_ZMK)) {
    if (key.toUpperCase() === upper) return value;
  }
  // Single letter
  if (/^[a-zA-Z]$/.test(trimmed)) return trimmed.toUpperCase();
  return 'TRANS';
}

/**
 * Generate ZMK firmware files for the keyboard.
 */
export function generateFirmware(
  layout: KeyboardLayout,
  matrix: SwitchMatrix,
  config: BuildConfig,
): FirmwareOutput {
  const boardName = config.project.name.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();

  const overlay = generateOverlay(layout, matrix, config, boardName);
  const keymap = generateKeymap(layout, matrix, config, boardName);
  const conf = generateConf(config);
  const metadata = generateMetadata(config, boardName);

  return { overlay, keymap, conf, metadata };
}

function generateOverlay(
  layout: KeyboardLayout,
  matrix: SwitchMatrix,
  config: BuildConfig,
  boardName: string,
): string {
  const rowPins = Array.from({ length: matrix.rows }, (_, i) => `<&gpio0 ${i + 2}>`);
  const colPins = Array.from({ length: matrix.cols }, (_, i) => `<&gpio0 ${i + matrix.rows + 2}>`);

  const direction = config.diode.direction === 'col2row' ? 'col2row' : 'row2col';

  let overlay = `/*
 * ${config.project.name} - ZMK Devicetree Overlay
 * Generated by keyboard-maker
 */

/ {
    chosen {
        zmk,kscan = &kscan0;
    };

    kscan0: kscan {
        compatible = "zmk,kscan-gpio-matrix";
        diode-direction = "${direction}";

        row-gpios
            = ${rowPins.join('\n            , ')};

        col-gpios
            = ${colPins.join('\n            , ')};
    };
`;

  // Add underglow if enabled
  if (config.features.rgbUnderglow && config.features.underglow.ledCount > 0) {
    overlay += `
    led_strip: ws2812@0 {
        compatible = "worldsemi,ws2812-spi";
        reg = <0>;
        chain-length = <${config.features.underglow.ledCount}>;
    };
`;
  }

  overlay += `};\n`;

  return overlay;
}

function generateKeymap(
  layout: KeyboardLayout,
  matrix: SwitchMatrix,
  config: BuildConfig,
  boardName: string,
): string {
  // Build the keymap matrix by row/col
  const keymapGrid: string[][] = [];
  for (let r = 0; r < matrix.rows; r++) {
    keymapGrid.push(new Array(matrix.cols).fill('&trans'));
  }

  // Fill in keycodes from layout labels
  for (const key of layout.keys) {
    const pos = matrix.assignments.get(key.id);
    if (!pos) continue;
    const label = key.labels[0] ?? '';
    const zmkCode = labelToZmkKeycode(label);
    if (zmkCode === 'TRANS') {
      keymapGrid[pos.row][pos.col] = '&trans';
    } else {
      keymapGrid[pos.row][pos.col] = `&kp ${zmkCode}`;
    }
  }

  // Format keymap rows
  const keymapRows = keymapGrid.map(row => `                ${row.join(' ')}`).join('\n');

  const hasBluetoothBindings = config.connectivity.bluetooth;
  const btLayer = hasBluetoothBindings
    ? `
        bt_layer {
            bindings = <
${keymapGrid.map(() => `                ${new Array(matrix.cols).fill('&trans').join(' ')}`).join('\n')}
            >;
        };`
    : '';

  return `/*
 * ${config.project.name} - ZMK Keymap
 * Generated by keyboard-maker
 */

#include <behaviors.dtsi>
#include <dt-bindings/zmk/keys.h>
${config.connectivity.bluetooth ? '#include <dt-bindings/zmk/bt.h>' : ''}

/ {
    keymap {
        compatible = "zmk,keymap";

        default_layer {
            bindings = <
${keymapRows}
            >;
        };${btLayer}
    };
};
`;
}

function generateConf(config: BuildConfig): string {
  const lines: string[] = [
    `# ${config.project.name} - ZMK Configuration`,
    `# Generated by keyboard-maker`,
    '',
    `CONFIG_ZMK_KEYBOARD_NAME="${config.project.name}"`,
    '',
  ];

  if (config.connectivity.bluetooth) {
    lines.push('# Bluetooth');
    lines.push('CONFIG_ZMK_BLE=y');
    lines.push('');
  }

  if (config.connectivity.usb) {
    lines.push('# USB');
    lines.push('CONFIG_ZMK_USB=y');
    lines.push('');
  }

  if (config.power.battery) {
    lines.push('# Battery reporting');
    lines.push('CONFIG_ZMK_BATTERY_REPORTING=y');
    lines.push('CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60');
    lines.push('');
  }

  if (config.features.rgbUnderglow) {
    lines.push('# RGB Underglow');
    lines.push('CONFIG_ZMK_RGB_UNDERGLOW=y');
    lines.push('CONFIG_WS2812_STRIP=y');
    lines.push(`CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=0`);
    lines.push(`CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100`);
    lines.push(`CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=50`);
    lines.push('');
  }

  // Deep sleep for battery-powered boards
  if (config.power.battery && config.firmware.features.includes('deep-sleep')) {
    lines.push('# Power management');
    lines.push('CONFIG_ZMK_SLEEP=y');
    lines.push('CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000');
    lines.push('');
  }

  return lines.join('\n');
}

function generateMetadata(config: BuildConfig, boardName: string): string {
  return `file_format: "2"
id: ${boardName}
name: ${config.project.name}
type: board
arch: arm
outputs:
${config.connectivity.usb ? '  - usb\n' : ''}${config.connectivity.bluetooth ? '  - ble\n' : ''}`;
}
