import { exportDSN } from './dsn-exporter.js';
import { runFreerouting } from './freerouter.js';
import { importSES } from './ses-importer.js';
import { join } from 'path';
import { writeFileSync, mkdirSync } from 'fs';
import type { BuildConfig, SwitchMatrix } from '../shared/types.js';

/**
 * Route a PCB based on the config's routing mode.
 *
 * - "auto": Full Freerouting pipeline (DSN export → route → SES import)
 * - "guided": Generate routing guide document + partial automation
 * - "manual": Skip routing, just output the guide
 *
 * @returns Path to the (possibly routed) PCB file
 */
export async function routePCB(
  pcbPath: string,
  outputDir: string,
  config: BuildConfig,
  matrix: SwitchMatrix,
  onLog?: (msg: string) => void,
  timeoutMinutes?: number,
  maxPasses?: number,
): Promise<string> {
  const mode = config.pcb.routing;

  // Always generate the routing guide
  writeRoutingGuide(outputDir, config, matrix);

  if (mode === 'manual') {
    return pcbPath;
  }

  if (mode === 'guided') {
    return pcbPath;
  }

  // Auto mode: Freerouting pipeline
  const dsnPath = join(outputDir, 'keyboard.dsn');
  const sesPath = join(outputDir, 'keyboard.ses');
  const routedPcbPath = join(outputDir, 'keyboard-routed.kicad_pcb');

  try {
    exportDSN(pcbPath, dsnPath);
    await runFreerouting(dsnPath, sesPath, onLog, timeoutMinutes, maxPasses);
    importSES(pcbPath, sesPath, routedPcbPath);
    return routedPcbPath;
  } catch (err: any) {
    const msg = `Auto-routing failed: ${err.message}`;
    console.log(`  ${msg}`);
    onLog?.(`  ${msg}`);
    console.log('  Falling back to unrouted PCB. See routing-guide.md for manual instructions.');
    return pcbPath;
  }
}

function writeRoutingGuide(outputDir: string, config: BuildConfig, matrix: SwitchMatrix): void {
  const guide = `# PCB Routing Guide

Generated by keyboard-maker for: ${config.project.name}
Matrix: ${matrix.rows} rows x ${matrix.cols} columns

## Routing Priority Order

1. **USB differential pair** (D+/D-)
   - Route first, keep traces parallel
   - Match lengths within 0.1mm
   - ~0.3mm trace width for 90ohm impedance on 2-layer PCB

2. **Power traces** (VBUS, 3V3, VBAT, GND)
   - Use 0.5mm trace width minimum
   - Place GND copper pour on back layer (B.Cu)
   - Route: USB-C VBUS → ESD → regulator → MCU
${config.power.battery ? `   - Battery: JST connector → charger IC → power switch → MCU VDD` : ''}

3. **Column traces** (COL0–COL${matrix.cols - 1})
   - Run vertically through the switch matrix
   - Route on front copper (F.Cu)
   - 0.25mm trace width

4. **Row traces** (ROW0–ROW${matrix.rows - 1})
   - Run horizontally, connecting diode cathodes
   - Route on back copper (B.Cu) to avoid crossing columns
   - 0.25mm trace width

5. **MCU connections**
   - Short stubs from row/col nets to MCU GPIO pads
${config.features.rgbPerKey ? `\n6. **LED data line**\n   - Daisy-chain from MCU through all LEDs\n   - Keep segments under 10cm` : ''}

## Layer Assignment (${config.pcb.layers ?? 2}-layer board)
${(config.pcb.layers ?? 2) >= 4 ? `
| Layer | Purpose |
|-------|---------|
| F.Cu (top) | Switch pads, MCU, USB-C, main components |
| In1.Cu (inner 1) | ${config.pcb.signalLayer === 1 ? 'Signal traces (ROW/COL) — primary routing layer' : 'Ground plane — provides return path and shielding'} |
| In2.Cu (inner 2) | ${config.pcb.signalLayer === 2 ? 'Signal traces (ROW/COL) — primary routing layer' : 'Power plane (VCC/VBUS) — clean power distribution'} |
| B.Cu (bottom) | Diodes, LEDs, ${config.pcb.signalLayer === 31 ? 'signal traces' : 'ground pour'} |

**4-layer benefits:** Dedicated ground/power planes reduce noise, improve signal integrity, and give the autorouter more room to route traces without crossing.
` : `
| Layer | Purpose |
|-------|---------|
| F.Cu (front) | Switches, column traces, MCU, USB-C, main components |
| B.Cu (back) | Diodes, row traces, ground pour |
`}

## Trace Widths

| Type | Width |
|------|-------|
| Signal | 0.25mm |
| Power | 0.5mm |
| USB D+/D- | 0.3mm (impedance matched) |

## Tips

- Use 45-degree or curved trace corners (never 90-degree)
- Keep traces ≥0.5mm from board edges
- Add stitching vias for ground pour every ~25mm
- Minimum via size: 0.3mm drill, 0.6mm annular ring
- Run DRC (Design Rule Check) in KiCad before exporting Gerbers

## Auto-Routing with Freerouting

If you chose manual routing but want to try auto-routing later:

\`\`\`bash
# Export DSN from KiCad
kicad-cli pcb export dsn --output keyboard.dsn keyboard.kicad_pcb

# Run Freerouting
java -jar ~/.local/bin/freerouting.jar -de keyboard.dsn -do keyboard.ses -mp 30

# Import results back in KiCad
# File → Import → Specctra Session → select keyboard.ses
\`\`\`
`;
  writeFileSync(join(outputDir, 'routing-guide.md'), guide);
}
